 CONTROL PARAMETERS
 ------------------
 sim_model                     : NUMERICAL (with theory)
 ae_flag                       : KINETIC ELECTRONS
 collision_model               : FULL LINEARIZED FOKKER-PLANCK
 equilibrium_model             : MILLER
 profile_model                 : LOCAL
 sign_q                        : NEGATIVE
 sign_bunit                    : POSITIVE (BT CW)
 rotation model                : ROTATION EFFECTS INCLUDED
 spitzer_model:                : OFF (NEOCLASSICAL TRANSPORT)
 threed_model:                 : AXISYMMETRIC EQUILIBRIUM

 GRID DIMENSIONS
 ---------------
 n_radial         :   1
 n_energy         :   6
 n_xi             :  17
 n_theta          :  17

 PHYSICS PARAMETERS
 ------------------
       r/a:  2.0028E-01
       R/a:  2.9382E+00        shift: -3.7584E-02
         q: -9.7273E-01            s:  2.9002E-01
      zmag:  5.9574E-02        dzmag:  3.4728E-03
     kappa:  1.2250E+00      s_kappa:  9.4773E-03
     delta:  2.1325E-02      s_delta:  3.1591E-02
      zeta:  5.4986E-04       s_zeta:  1.3841E-02
      sin3:  0.0000E+00       s_sin3:  0.0000E+00
      sin4:  0.0000E+00       s_sin4:  0.0000E+00
      sin5:  0.0000E+00       s_sin5:  0.0000E+00
      sin6:  0.0000E+00       s_sin6:  0.0000E+00
      cos0:  0.0000E+00       s_cos0:  0.0000E+00
      cos1:  0.0000E+00       s_cos1:  0.0000E+00
      cos2:  0.0000E+00       s_cos2:  0.0000E+00
      cos3:  0.0000E+00       s_cos3:  0.0000E+00
      cos4:  0.0000E+00       s_cos4:  0.0000E+00
      cos5:  0.0000E+00       s_cos5:  0.0000E+00
      cos6:  0.0000E+00       s_cos6:  0.0000E+00

  dphi0/dr:  0.0000E+00
     omega: -1.8989E-01    domega/dr:  4.2760E-01
     epar0:  0.0000E+00

indx   z       n/n_norm     T/T_norm     m/m_norm     a/Ln         a/Lt         nu
  1    1.000   8.3540E-01   1.2678E+00   1.0000E+00   5.7518E-02   9.3242E-01   2.8567E-04
  2    6.000   2.7433E-02   1.2678E+00   6.0001E+00   1.3788E+00   9.3242E-01   4.9634E-03
  3   -1.000   1.0000E+00   1.0000E+00   2.7231E-04   2.7500E-01   1.4132E+00   2.9581E-02
 ------------------

 Estimated memory (GB) =  0.49326E+00
 Begin matrix factor -- UMFPACK
 Done matrix factor -- UMFPACK
 Begin matrix solve -- UMFPACK
 Done matrix solve -- UMFPACK

 r/a =                 0.20028E+00
 jpar =               -0.33756E-01
 sum Z_s Gamma_s =     0.45944E-08
  Z       pflux         eflux         mflux
  1.000  -0.15304E-06   0.66235E-06   0.28019E-06
  6.000   0.26668E-07   0.13853E-06  -0.28071E-06
 -1.000   0.23701E-08   0.37915E-07   0.57586E-11
 ------------------

