 CONTROL PARAMETERS
 ------------------
 sim_model                     : NUMERICAL (with theory)
 ae_flag                       : KINETIC ELECTRONS
 collision_model               : FULL LINEARIZED FOKKER-PLANCK
 equilibrium_model             : MILLER
 profile_model                 : LOCAL
 sign_q                        : POSITIVE
 sign_bunit                    : NEGATIVE (BT CCW)
 rotation model                : ROTATION EFFECTS NOT INCLUDED
 spitzer_model:                : OFF (NEOCLASSICAL TRANSPORT)
 threed_model:                 : AXISYMMETRIC EQUILIBRIUM

 GRID DIMENSIONS
 ---------------
 n_radial         :   1
 n_energy         :   6
 n_xi             :  17
 n_theta          :  17

 PHYSICS PARAMETERS
 ------------------
       r/a:  2.0028E-01
       R/a:  2.9382E+00        shift:  3.7584E-02
         q:  9.7273E-01            s:  2.9002E-01
      zmag:  0.0000E+00        dzmag:  0.0000E+00
     kappa:  1.2250E+00      s_kappa:  9.4773E-03
     delta:  2.1325E-02      s_delta:  3.1591E-02
      zeta:  5.4986E-04       s_zeta:  1.3841E-02
      sin3:  0.0000E+00       s_sin3:  0.0000E+00
      sin4:  0.0000E+00       s_sin4:  0.0000E+00
      sin5:  0.0000E+00       s_sin5:  0.0000E+00
      sin6:  0.0000E+00       s_sin6:  0.0000E+00
      cos0:  0.0000E+00       s_cos0:  0.0000E+00
      cos1:  0.0000E+00       s_cos1:  0.0000E+00
      cos2:  0.0000E+00       s_cos2:  0.0000E+00
      cos3:  0.0000E+00       s_cos3:  0.0000E+00
      cos4:  0.0000E+00       s_cos4:  0.0000E+00
      cos5:  0.0000E+00       s_cos5:  0.0000E+00
      cos6:  0.0000E+00       s_cos6:  0.0000E+00

  dphi0/dr:  0.0000E+00
     omega:  0.0000E+00    domega/dr:  0.0000E+00
     epar0:  0.0000E+00

indx   z       n/n_norm     T/T_norm     m/m_norm     a/Ln         a/Lt         nu
  1   -1.000   1.0000E+00   1.0000E+00   2.7238E-04   4.6357E-03   2.3822E-02   2.6836E-16
  2    1.000   7.9497E-01   1.2678E+00   9.9305E-01  -6.2978E-04   1.5718E-02   2.4751E-18
  3    6.000   2.7433E-02   1.2678E+00   5.9583E+00   2.3242E-02   1.5718E-02   4.5191E-17
 ------------------

 Estimated memory (GB) =  0.49326E+00
 Begin matrix factor -- UMFPACK
 Done matrix factor -- UMFPACK
 Begin matrix solve -- UMFPACK
 Done matrix solve -- UMFPACK

 r/a =                 0.20028E+00
 jpar =                0.95512E-03
 sum Z_s Gamma_s =     0.32575E-19
  Z       pflux         eflux         mflux
 -1.000   0.10816E-19  -0.51575E-18   0.88607E-20
  1.000   0.47955E-19  -0.18189E-19   0.17639E-17
  6.000  -0.76068E-21   0.18492E-18   0.51296E-20
 ------------------

