 CONTROL PARAMETERS
 ------------------
 sim_model                     : NUMERICAL (with theory)
 ae_flag                       : KINETIC ELECTRONS
 collision_model               : FULL LINEARIZED FOKKER-PLANCK
 equilibrium_model             : MILLER
 profile_model                 : LOCAL
 sign_q                        : NEGATIVE
 sign_bunit                    : NEGATIVE (BT CCW)
 rotation model                : ROTATION EFFECTS INCLUDED
 spitzer_model:                : OFF (NEOCLASSICAL TRANSPORT)
 threed_model:                 : AXISYMMETRIC EQUILIBRIUM
 
 GRID DIMENSIONS
 ---------------
 n_radial         :   1
 n_energy         :   6
 n_xi             :  17
 n_theta          :  17
 
 PHYSICS PARAMETERS
 ------------------
       r/a:  5.5040E-01
       R/a:  3.6549E+00        shift: -4.3131E-01
         q: -3.8161E+00            s:  3.7021E-01
      zmag: -4.4599E-05        dzmag: -8.4867E-04
     kappa:  1.9037E+00      s_kappa:  3.0287E-01
     delta:  3.7047E-01      s_delta:  5.5573E-01
      zeta: -2.6551E-03       s_zeta: -4.7318E-02
      sin3:  0.0000E+00       s_sin3:  0.0000E+00
      sin4:  0.0000E+00       s_sin4:  0.0000E+00
      sin5:  0.0000E+00       s_sin5:  0.0000E+00
      sin6:  0.0000E+00       s_sin6:  0.0000E+00
      cos0:  0.0000E+00       s_cos0:  0.0000E+00
      cos1:  0.0000E+00       s_cos1:  0.0000E+00
      cos2:  0.0000E+00       s_cos2:  0.0000E+00
      cos3:  0.0000E+00       s_cos3:  0.0000E+00
      cos4:  0.0000E+00       s_cos4:  0.0000E+00
      cos5:  0.0000E+00       s_cos5:  0.0000E+00
      cos6:  0.0000E+00       s_cos6:  0.0000E+00
 
  dphi0/dr:  0.0000E+00
     omega: -6.6815E-06    domega/dr:  1.9356E-05
     epar0:  0.0000E+00
 
indx   z       n/n_norm     T/T_norm     m/m_norm     a/Ln         a/Lt         nu
  1    1.000   4.3619E-01   8.8280E-01   1.0005E+00   3.1377E-01   1.2067E+00   1.1516E-04
  2    1.000   4.3619E-01   8.8280E-01   1.5007E+00   3.1377E-01   1.2067E+00   9.4031E-05
  3    2.000   5.0000E-02   8.8280E-01   2.0010E+00   3.3021E-01   1.2067E+00   1.4936E-04
  4   36.000   7.1429E-04   8.8280E-01   4.2020E+01   3.3022E-01   1.2067E+00   4.8877E-02
  5   -1.000   1.0000E+00   1.0000E+00   2.7244E-04   3.3021E-01   1.2591E+00   1.3271E-02
 ------------------
 
 WARNING: (NEO) ROTATION IS BEING RUN WITHOUT QN DENSITIES
 Estimated memory (GB) =  0.94434E+00
 Begin matrix factor -- UMFPACK
 ERROR: (NEO) Matrix factorization failed in neo_sparse_solve
 uinfo=   -4                             
 Estimated memory (GB) =  0.18702E+01
 Re-trying matrix factorization -- UMFPACK
 Done matrix factor -- UMFPACK
 Begin matrix solve -- UMFPACK
 Done matrix solve -- UMFPACK
 
 r/a =                 0.55040E+00
 jpar =                0.10988E-01
 sum Z_s Gamma_s =    -0.13360E-11
  Z       pflux         eflux         mflux
  1.000  -0.17182E-08   0.43333E-07  -0.31864E-09
  1.000   0.49658E-09   0.58827E-07  -0.47879E-09
  2.000   0.34931E-09   0.63831E-08  -0.18452E-10
 36.000   0.34903E-10   0.11070E-09  -0.33858E-12
 -1.000   0.73483E-09   0.36940E-08  -0.26694E-12
 ------------------
 
 CONTROL PARAMETERS
 ------------------
 sim_model                     : NUMERICAL (with theory)
 ae_flag                       : KINETIC ELECTRONS
 collision_model               : FULL LINEARIZED FOKKER-PLANCK
 equilibrium_model             : MILLER
 profile_model                 : LOCAL
 sign_q                        : NEGATIVE
 sign_bunit                    : NEGATIVE (BT CCW)
 rotation model                : ROTATION EFFECTS INCLUDED
 spitzer_model:                : OFF (NEOCLASSICAL TRANSPORT)
 threed_model:                 : AXISYMMETRIC EQUILIBRIUM
 
 GRID DIMENSIONS
 ---------------
 n_radial         :   1
 n_energy         :   6
 n_xi             :  17
 n_theta          :  17
 
 PHYSICS PARAMETERS
 ------------------
       r/a:  5.5040E-01
       R/a:  3.6549E+00        shift: -4.3131E-01
         q: -3.8161E+00            s:  3.7021E-01
      zmag: -4.4599E-05        dzmag: -8.4867E-04
     kappa:  1.9037E+00      s_kappa:  3.0287E-01
     delta:  3.7047E-01      s_delta:  5.5573E-01
      zeta: -2.6551E-03       s_zeta: -4.7318E-02
      sin3:  0.0000E+00       s_sin3:  0.0000E+00
      sin4:  0.0000E+00       s_sin4:  0.0000E+00
      sin5:  0.0000E+00       s_sin5:  0.0000E+00
      sin6:  0.0000E+00       s_sin6:  0.0000E+00
      cos0:  0.0000E+00       s_cos0:  0.0000E+00
      cos1:  0.0000E+00       s_cos1:  0.0000E+00
      cos2:  0.0000E+00       s_cos2:  0.0000E+00
      cos3:  0.0000E+00       s_cos3:  0.0000E+00
      cos4:  0.0000E+00       s_cos4:  0.0000E+00
      cos5:  0.0000E+00       s_cos5:  0.0000E+00
      cos6:  0.0000E+00       s_cos6:  0.0000E+00
 
  dphi0/dr:  0.0000E+00
     omega: -6.6815E-06    domega/dr:  1.9356E-05
     epar0:  0.0000E+00
 
indx   z       n/n_norm     T/T_norm     m/m_norm     a/Ln         a/Lt         nu
  1    1.000   4.3619E-01   8.8280E-01   1.0005E+00   3.1377E-01   1.2067E+00   1.1516E-04
  2    1.000   4.3619E-01   8.8280E-01   1.5007E+00   3.1377E-01   1.2067E+00   9.4031E-05
  3    2.000   5.0000E-02   8.8280E-01   2.0010E+00   3.3021E-01   1.2067E+00   1.4936E-04
  4   36.000   7.1429E-04   8.8280E-01   4.2020E+01   3.3022E-01   1.2067E+00   4.8877E-02
  5   -1.000   1.0000E+00   1.0000E+00   2.7244E-04   3.3021E-01   1.2591E+00   1.3271E-02
 ------------------
 
 WARNING: (NEO) ROTATION IS BEING RUN WITHOUT QN DENSITIES
